[project]
name = "ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "msaimanish", email = "msaimanishreddy123@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.142.2",
    "httpx>=0.28.1",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "torch>=2.14.1",
    "torchvision>=0.29.1",
    "uvicorn>=0.54.0",
    "xgboost>=3.4.1",
]

[project.scripts]
ml = "ml:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
