"""add operational observations

Revision ID: b2ffc0660162
Revises: a328f8f80ec5
Create Date: 2026-10-04 10:17:56.914496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ffc0660162'
down_revision: Union[str, Sequence[str], None] = 'a328f8f80ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operational_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('occupancy_ratio', sa.Float(), nullable=False),
    sa.Column('queue_length', sa.Float(), nullable=False),
    sa.Column('event_delay_minutes', sa.Float(), nullable=False),
    sa.Column('vendor_delay_minutes', sa.Float(), nullable=False),
    sa.Column('equipment_failure_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operational_observations')
    # ### end Alembic commands ###
